# Generated by Django 5.2.3 on 2025-09-19 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='advance_hours',
            field=models.IntegerField(default=4, help_text='予約可能になる時間（現在時刻から何時間後）'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0), help_text='営業終了時間'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='friday_open',
            field=models.BooleanField(default=True, verbose_name='金曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='monday_open',
            field=models.BooleanField(default=True, verbose_name='月曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='saturday_open',
            field=models.BooleanField(default=True, verbose_name='土曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slot_duration',
            field=models.IntegerField(default=60, help_text='予約枠の長さ（分）'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='営業開始時間'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sunday_open',
            field=models.BooleanField(default=True, verbose_name='日曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='thursday_open',
            field=models.BooleanField(default=True, verbose_name='木曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tuesday_open',
            field=models.BooleanField(default=True, verbose_name='火曜日営業'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='wednesday_open',
            field=models.BooleanField(default=True, verbose_name='水曜日営業'),
        ),
    ]
