# Generated by Django 5.2.3 on 2025-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_tenant_advance_hours_tenant_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', '顧客'), ('owner', '事業者'), ('developer', '開発者')], default='customer', max_length=20, verbose_name='ユーザー種別'),
        ),
    ]
