# Generated by Django 5.2.3 on 2025-09-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_add_timestamps'),
        ('reservations', '0004_customuser_role'),
    ]

    operations = [
    ]
