# Generated by Django 5.2.3 on 2025-09-19 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_merge_0002_add_timestamps_0004_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name'], 'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', '-time_slot'], 'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'テナント', 'verbose_name_plural': 'テナント'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='メニュー名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='reservations.tenant', verbose_name='テナント'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='予約作成日時'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.menu', verbose_name='メニュー'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.tenant', verbose_name='テナント'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.TimeField(verbose_name='予約時間'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='advance_hours',
            field=models.IntegerField(default=4, help_text='予約可能になる時間（現在時刻から何時間後）0-168時間', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL, verbose_name='オーナー'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slot_duration',
            field=models.IntegerField(default=60, help_text='予約枠の長さ（分）15-240分', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL識別子'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('tenant', 'date', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'date'], name='reservation_tenant__6a1842_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'time_slot'], name='reservation_date_40c1cb_idx'),
        ),
    ]
