# Generated by Django 5.2.3 on 2025-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_menu_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='電話番号'),
        ),
    ]
