# Generated by Django 5.2.3 on 2025-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号'),
        ),
    ]
