# Generated by Django 5.2.6 on 2025-09-22 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='予約確認メール送信用', max_length=254, null=True, verbose_name='顧客メールアドレス'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='人数'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='特別なご要望'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='キャンセルに関するポリシー（任意）', null=True, verbose_name='キャンセルポリシー'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_confirmation_message',
            field=models.TextField(blank=True, help_text='予約者に送信する確認メールのカスタムメッセージ（任意）', null=True, verbose_name='予約確認カスタムメッセージ'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_notice_message',
            field=models.TextField(blank=True, help_text='来店前にお客様に伝えたい注意事項（任意）', null=True, verbose_name='来店前注意事項'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, help_text='予約通知を受け取るメールアドレス', max_length=254, null=True, verbose_name='通知用メールアドレス'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
