# Generated by Django 5.2.6 on 2025-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='cancellation_policy',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='custom_confirmation_message',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='custom_notice_message',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.AddField(
            model_name='tenant',
            name='customer_email_message',
            field=models.TextField(default='{お客様名} 様\n\n{店舗名}のご予約が完了いたしました。\n\n■予約詳細\n予約日時: {予約日時}\nお名前: {お客様名}\n電話番号: {電話番号}\n\n何かご不明な点がございましたら、お気軽にお問い合わせください。\nお客様のご来店を心よりお待ちしております。\n\n{店舗名}', help_text='使用可能な変数: {店舗名}、{お客様名}、{予約日時}、{電話番号}、{メールアドレス}', verbose_name='予約確認メール本文'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='customer_email_subject',
            field=models.CharField(default='【予約確認】{店舗名}のご予約が完了しました', help_text='{店舗名}、{お客様名}、{予約日時}が使用できます', max_length=200, verbose_name='予約確認メール件名'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='予約通知を受け取るメールアドレス（空の場合はオーナーのメールアドレスを使用）', max_length=254, null=True, verbose_name='通知先メールアドレス'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_email_message',
            field=models.TextField(default='{店舗名} 様\n\n新しいご予約が入りました。\n\n■予約詳細\nお客様名: {お客様名}\n予約日時: {予約日時}\n電話番号: {電話番号}\nメールアドレス: {メールアドレス}\n\n管理画面で詳細をご確認ください。', help_text='使用可能な変数: {店舗名}、{お客様名}、{予約日時}、{電話番号}、{メールアドレス}', verbose_name='予約通知メール本文'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_email_subject',
            field=models.CharField(default='【新規予約】{お客様名}様からご予約がありました', help_text='{店舗名}、{お客様名}、{予約日時}が使用できます', max_length=200, verbose_name='予約通知メール件名'),
        ),
    ]
